name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Define tool versions
      DART_SASS_VERSION: 1.102.0
      GO_VERSION: 1.26.5
      HUGO_VERSION: 0.165.0
      NODE_VERSION: 24.19.0

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: false
      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@v2.5.0
        env:
          HUGO_VERSION: ${{ env.HUGO_VERSION }}
          TARGET_REPO: emossman/ski-and-board-club
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t ananke'
